apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: brightbox-volume-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: brightbox-volume-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: brightbox-volume-device-plugin
    spec:
      containers:
      - name: brightbox-volume-device-plugin
        image: brightbox/brightbox-volume-device-plugin:latest 
        args: ["-v", "4", "-logtostderr"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: disk-details
            mountPath: /dev/disk
            readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: disk-details
          hostPath:
            path: /dev/disk
